#!/bin/bash
# https://superuser.com/questions/1333674/how-do-i-disable-kernel-logging-into-the-systemd-journal
# https://bbs.archlinux.org/viewtopic.php?id=172639
# https://forum.manjaro.org/t/limit-journald-logging-service-and-speed-up-boot-time/12342
# https://wiki.archlinux.org/index.php/silent_boot
# https://www.youtube.com/watch?v=tuqhsqrhXk0
# https://github.com/systemd/systemd/issues/801
# https://wiki.archlinux.org/index.php/Systemd/Journal

# In Arch Linux, the directory /var/log/journal/ is a part of the systemd package,
# and the journal (when Storage= is set to auto in /etc/systemd/journald.conf) will
# write to /var/log/journal/. If that directory is deleted, systemd will not recreate
# it automatically and instead will write its logs to /run/systemd/journal in a
# nonpersistent way. However, the folder will be recreated if Storage=persistent is
# added to journald.conf and systemd-journald.service is restarted (or the system is rebooted). 

# https://www.freedesktop.org/software/systemd/man/journald.conf.html

# Storage= Controls where to store journal data. One of "volatile", "persistent", "auto" and
# "none". If "volatile", journal log data will be stored only in memory, i.e. below the
# /run/log/journal hierarchy (which is created if needed). If "persistent", data will be stored
# preferably on disk, i.e. below the /var/log/journal hierarchy (which is created if needed),
# with a fallback to /run/log/journal (which is created if needed), during early boot and if the
# disk is not writable. "auto" is similar to "persistent" but the directory /var/log/journal is
# not created if needed, so that its existence controls where log data goes. "none" turns off all
# storage, all log data received will be dropped. Forwarding to other targets, such as the console,
# the kernel log buffer, or a syslog socket will still work however. Defaults to "auto".

# /etc/systemd/journald.conf

echo ""
echo "Disabling storage for systemd-journald."
echo ""

systemctl stop systemd-journald
rm -rf /var/log/journal/
sync

echo "Done. No reboot required."
echo ""
