#!/bin/bash

# Script to improve performance and endurance for Debian with SystemD (Debian 9+).
# Crafted to be repeatedly run without issues.

# --- Run as your user.

if [[ ${EUID} -eq 0 ]]; then
  echo ""
  echo "Run this one as your user, not as root."
  echo ""
  exit 1
fi

# --- Asking for wait.

echo ""
echo "Working, please wait..."
echo ""

# --- Mozilla Firefox needs to be closed

ps -ef | grep -v grep | grep -q firefox
if [ $? -eq 0 ]
then
  echo ""
  echo "Mozilla Firefox is open. Closing it in:"
  echo ""
  sleep 1
  echo "3"
  echo ""
  sleep 1
  echo "2"
  echo ""
  sleep 1
  echo "1"
  echo ""
  sleep 1
  killall -e /usr/lib/firefox-esr/firefox-esr
  sync
  sleep 5
  sync
fi

# --- Chromium needs to be closed

ps -ef | grep -v grep | grep -q chromium
if [ $? -eq 0 ]
then
  echo ""
  echo "Chromium is open. Closing it in:"
  echo ""
  sleep 1
  echo "3"
  echo ""
  sleep 1
  echo "2"
  echo ""
  sleep 1
  echo "1"
  echo ""
  sleep 1
  killall -e /usr/lib/chromium/chromium
  sync
  sleep 5
  sync
fi


# --- Mozilla Firefox cache in /tmp

mkdir -p /home/$USER/.cache/mozilla
rm -rf /home/$USER/.cache/mozilla
ln -s /tmp /home/$USER/.cache/mozilla

# --- Chromium cache in /tmp

mkdir -p /home/$USER/.cache/chromium
rm -rf /home/$USER/.cache/chromium
ln -s /tmp /home/$USER/.cache/chromium

# Firefox, Chromium will create and use this busy folders inside /tmp:

# /tmp/firefox
# /tmp/Default

# You can check /tmp is the most used for internet browsing:

# find / -xdev -printf '%T+ %P\n' | sort -n | tail -99

# Configure mpv for hardware decoding on Intel and Amd and Ati graphic cards
# Put vdpau instead of vaapi if you have proprietary nvidia drivers
mkdir -p /home/$USER/.config/mpv
cat <<EOF > /home/$USER/.config/mpv/mpv.conf
# https://github.com/mpv-player/mpv/issues/5711
# https://www.reddit.com/r/nhl_games/comments/5ea3an/increasing_cachereadahead_in_mpv/
# only with vo=vaapi you can't acces ui movie scroll bar
hwdec=vaapi
vo=gpu
gpu-context=x11egl
#hwdec=vaapi
#vo=vaapi
save-position-on-quit
audio-normalize-downmix=yes
audio-channels=stereo
volume=100
demuxer-thread=yes
demuxer-readahead-secs=200
fullscreen
EOF

# --- Done.

sync
echo ""
echo "No reboot required. Done."
echo ""
